# Generated by Django 4.0.5 on 2022-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coast', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('name', models.TextField(max_length=1000, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('popular', models.FloatField(default=0, verbose_name='Популярность')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('division', models.BooleanField(blank=True, default=False, null=True, verbose_name='Разделение')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
