# Generated by Django 4.0.5 on 2022-06-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0004_category_contacts_customer_photos_timetable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Порядок', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['id'], 'verbose_name': 'Текст', 'verbose_name_plural': 'Texts'},
        ),
    ]
