# Generated by Django 4.0.5 on 2022-06-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0005_alter_image_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.purchase', verbose_name=' Корзина'),
            preserve_default=False,
        ),
    ]
