# Generated by Django 4.0.5 on 2022-07-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0007_alter_benefits_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='product',
        ),
    ]
