# Generated by Django 4.0.5 on 2022-07-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferumbel', '0008_remove_photos_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferumbel.product'),
        ),
    ]
